project:
  type: website
  output-dir: docs

website:
  title: "GESIS meets Copernicus (GxC)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Tutorials
        menu:
          - href: eod_intro.qmd
            text: Intro to EOD
          - href: raster_data.qmd
            text: Raster data
          - href: issp.qmd
            text: Case study ISSP
      - href: package.qmd
        text: Package
      - href: courses.qmd
        text: Courses
      - href: articles.qmd
        text: Articles
      - href: about.qmd
        text: About

bibliography: bib/references.bib
csl: bib/apa-single-spaced.csl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

execute:
  echo: true
  eval: true
  warning: true
  message: true
