project:
  type: website
  output-dir: docs

website:
  title: "GESIS meets Copernicus (GxC)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Tutorials
        menu:
          - href: eod_intro.qmd
            text: Intro to EO data
          - href: quality_criteria.qmd
            text: Quality criteria
          - href: raster_data.qmd
            text: Raster data
          - href: datacubes.qmd
            text: Datacubes
          - href: graphicdisplay.qmd  
            text: Graphic Display
          - href: nightlights.qmd
            text: Nightlights
          - href: issp.qmd
            text: Case study ISSP
          - href: gles_panel.qmd
            text: Case study GLES Panel
          - href: resources.qmd
            text: Further resources
      - text: Software
        menu:
          - href: package.qmd
            text: gxc package
          - href: catalogue.qmd
            text: Indicators
          - href: performance.qmd
            text: Performance
      - href: courses.qmd
        text: Courses
      - href: articles.qmd
        text: Articles
      - href: about.qmd
        text: About
      - href: mailinglist.qmd
        text: Mailing list
      - href: imprint.qmd
        text: Imprint

bibliography: bib/references.bib
csl: bib/apa-single-spaced.csl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

execute:
  echo: true
  eval: true
  warning: true
  message: true
