---
title: "Articles"
---

## Working papers

- Jessica Haak, Dennis Abel & Stefan Jünger. "**How extreme weather exposure and fear shape climate policy support across political orientation**"

- Abel, Dennis & Stefan Jünger. "**Earth Observation Data in the Social Sciences - Opportunities and Limitations**"

- Abel, Dennis, Manuel Linsenmeier & Stefan Jünger. "**GeoCliP-GER - A georeferenced local climate policy database for Germany**"

- Abel, Dennis & Stefan Jünger. "**How flooding events shape subjective risk perceptions and climate change opinion**"

- Jünger, Stefan, Dennis Abel & Anne Stroppe. "**The uncertain geographic context problem and the unknown effect of extreme weather on climate change attitudes**"

- Jochen Schanze, Dieter Gerten, Miriam Prys-Hansen, Dennis Abel, Jonathan F. Donges, Patrick Flamm, Mark Gessner, Marion Glaser, Detlef Gronenborn, Hans-Peter Grossart, Olaf Jöris, Wolfgang Lucht, Nils Moosdorf, Sonja Peterson & Barbara Warner. "**Earth and Societies – Integrated research on the Anthropocene**"

## Published


