---
title: "Courses and workshops"
---

## Upcoming

- GESIS Workshop "**Advanced Geospatial Data Processing for Social Scientists**", April 28/29 2025

- GESIS Workshop "**Introduction to Geospatial Techniques for Social Scientists in R**", April 09/10 2025

## Past events

- International Expert Workshop on "**Earth Observation Data in the Social Sciences**",
27-29 November 2024 at GESIS - Leibniz Institute for Social Sciences.

- Methods Primer on "**Working with Earth Observation data in R**", 31 October 2024, MethodsNET Launch Conference at UCLouvain, Belgium. The slides are accessible [here](slides/primer.html){target="_blank"}.

- GESIS Workshop on "**Introduction to Geospatial Techniques for Social Scientists in R**", including matters relevant for Earth Observation Data, April 23/24 2024. All the materials are accessible [here](https://github.com/StefanJuenger/gesis-workshop-geospatial-techniques-R-2024)

- International Expert Workshop on "**Earth Observation Data in the Social Sciences**",
13-15 December 2023 at GESIS - Leibniz Institute for Social Sciences. Check out
a few impressions from the workshop in this [video](https://youtu.be/iW4onh38UmA).